baseURL = "https://pretty-manicure.netlify.app"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Harold Talks Tech | My Portfolio"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = "4"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "Truong Sa, Ward 2, Phu Nhuan District, HCMC, Vietnam"
author = "Harold Hoang"
copyright = "Copyright &copy; 2021 Harold Hoang | A Theme by [gethugothemes](https://gethugothemes.com)"
description = "My Personal Portfolio Webpage"
email = "mhuy2003@gmail.com"
google_analitycs_id = "UA-122642609-3"
home = "Home"
logo = "images/logo.png"
phone = "+84 933 788 942"
theme_color = "#6CB36E"
[params.contact]
enable = true
form_action = "submit"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/haroldhuyhoang"
icon = "ti-facebook"
[[params.social]]
URL = "https://pretty-manicure.netlify.app"
icon = "ti-write"
[[params.social]]
URL = "https://github.com/HaroldH2003"
icon = "ti-github"
[[params.social]]
URL = "https://twitter.com/Piggy_Harold"
icon = "ti-twitter-alt"
